### ISSUE TITLE
TextEditor.displayBuffer is deprecated.

### ISSUE THREAD

**Issue by TiagoSoares** [jenius/atom-fold-comments#22] opened 2018-04-30 09:22 UTC
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.displayBuffer (<embedded>:2472:16)
<unknown> (/Users/Work/.atom/packages/fold-comments/lib/fold-comments.coffee:32:26)
Workspace.observeTextEditors (<embedded>:28518:59)
Object.activate (/Users/Work/.atom/packages/fold-comments/lib/fold-comments.coffee:30:31)
Package.activateNow (<embedded>:72537:33)
activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (<embedded>:73172:28)
```

**Comment by jescalan** [comment] 2018-04-30 15:45
Exact duplicate of #20

**Closed as completed by jescalan** 2018-04-30 15:45 UTC
