### ISSUE TITLE
TextEditor.displayBuffer is deprecated.

### ISSUE THREAD

**Issue by CristianRoibu** [jenius/atom-fold-comments#21] opened 2018-04-04 06:45 UTC
`TextEditor.prototype.displayBuffer` has always been private, but now
it is gone. Reading the `displayBuffer` property now returns a reference
to the containing `TextEditor`, which now provides *some* of the API of
the defunct `DisplayBuffer` class.
```
TextEditor.displayBuffer (<embedded>:2471:16)
<unknown> (/home/cross/.atom/packages/fold-comments/lib/fold-comments.coffee:32:26)
Workspace.observeTextEditors (<embedded>:28328:15)
Object.activate (/home/cross/.atom/packages/fold-comments/lib/fold-comments.coffee:30:31)
Package.activateNow (<embedded>:72392:33)
activationCommandSubscriptions.add.commandRegistry.onWillDispatch.event (<embedded>:73027:28)
```

**Comment by jescalan** [comment] 2018-04-04 17:24
Disturbingly exact duplicate of https://github.com/jescalan/atom-fold-comments/issues/20

**Closed as completed by jescalan** 2018-04-04 17:24 UTC
